name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  execute-scripts:

    runs-on: ubuntu-latest
    container:
      image: quay.io/fenicsproject/stable

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libgl1-mesa-glx xvfb -y
        pip3 install --upgrade pip
        pip3 install pyvista==0.36.1
    - uses: actions/checkout@v3
    - name: Run
      run: |
        bash run.sh
    - name: Add Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plots
        path: |
          data/dumbel/eps_0.01000000.vtu.png
          data/dumbel/eps_0.01000015.vtu.png
          data/dumbel/eps_0.01000101.vtu.png

          data/dumbel/eps_0.2000000.vtu.png
          data/dumbel/eps_0.2000015.vtu.png
          data/dumbel/eps_0.2000101.vtu.png

          data/bump/eps_0.01000000.vtu.png
          data/bump/eps_0.01000015.vtu.png
          data/bump/eps_0.01000101.vtu.png

          data/bump/eps_0.2000000.vtu.png
          data/bump/eps_0.2000015.vtu.png
          data/bump/eps_0.2000101.vtu.png
